import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Menu from "./menu";
import Footer from "./footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Yann Dubois OUAFETE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col m-10 ">
           <div className="flex  items-center   ">
             <div  className="font-serif text-5xl">Bergen</div>
              <Menu />
            </div>
            <div className=" flex justify-center items-center h-screen">{children}</div>
             <div className="flex bg-gray-200 h-100">
                <Footer />
             </div>
          </div>
      </body>
    </html>
  );
}
